# Generated by Django 2.0.4 on 2020-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='GoodsSPU',
        ),
    ]
