# Generated by Django 2.0.4 on 2020-04-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200420_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='detail',
        ),
    ]
