# Generated by Django 2.0.4 on 2020-04-20 14:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_goods_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, verbose_name='商品详情'),
        ),
    ]
