# Generated by Django 2.0.4 on 2020-04-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200420_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='commnet',
            new_name='comment',
        ),
    ]
